version: '2'
services:
  alertmanager-to-statuspage:
    image: shalb/alertmanager-to-statuspage:0.0.1
    volumes:
      - ./exporter:/opt/exporter
    restart: always
    ports:
      - "127.0.0.1:9647:9647"
    environment:
     #- URL=https://api.statuspage.io/v1/pages/{}/components/{}
      - API_KEY=00000000-0000-0000-0000-000000000000
     #- KEYS_TO_EXCLUDE=runbook_url externalURL generatorURL
     #- TEST_ALERTS_OPEN=test_alerts_open.json
     #- TEST_ALERTS_CLOSE=test_alerts_close.json
     #- LOG_LEVEL=INFO|DEBUG
      - LOG_LEVEL=DEBUG
     #- ALERT_TO_STATUSPAGE_TIMEOUT=10
     #- MAIN_LOOP_SLEEP_INTERVAL=10
     #- LISTEN_PORT=9647
   #entrypoint: ["/bin/bash", "-c", "sleep 9999"]
